server:
  port: 9090
  servlet:
    context-path: /api
spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/lntt
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
jwt:
  secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
  expiration: 3600000
